name: webviewx
description: A feature-rich cross-platform webview using webview_flutter for
  mobile and iframe for web. JS interop-ready.
homepage: https://github.com/adrianflutur/webviewx
version: 0.4.1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  path: ^1.8.1
  pointer_interceptor: ^0.9.3+2
  uuid: ^4.0.0
  webview_flutter: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.2
